server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: health-code
          uri: lb://health-code
          predicates:
            - Path=/health-code/**

