server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
    gateway:
      routes:
        - id: health-code
          uri: lb://health-code
          predicates:
            - Path=/health-code/**
        - id: itinerary-code
          uri: lb://itinerary-code
          predicates:
            - Path=/itinerary-code/**
        - id: place-code
          uri: lb://place-code
          predicates:
            - Path=/place-code/**
        - id: nucleic-acids
          uri: lb://nucleic-acids
          predicates:
            - Path=/nucleic-acids/**
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
#      default-filters:
#        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST